import { PaymentStatus, PoolStatus, Prisma, WithdrawalStatus } from '@prisma/client';
import { prisma } from '@/server/db/prisma';
import { completeMockPayment } from '@/server/services/allocation';
import { assertMockPaymentControlsEnabled, isValidMockPaymentTransition } from '@/server/payments/mock-controls';
import { requirePermission, type Permission, type Role } from '@/server/permissions/rbac';
import { safeCapacityUtilization } from '@/lib/safe-math';

export function assertAdmin(role: Role, permission: Permission) { requirePermission(role, permission); }
export async function audit(actorId: string, action: string, entityType: string, entityId: string | null, description: string, metadata?: Prisma.InputJsonValue) { return prisma.auditLog.create({ data: { actorId, action, entityType, entityId: entityId ?? undefined, description, metadata } }); }
export async function getAdminOverview() {
  const [totalUsers, activeUsers, totalAllocations, activeAllocations, pools, pendingPayments, completedPayments, pendingWithdrawals, withdrawals, openTickets, alerts, auditLogs] = await Promise.all([
    prisma.user.count(), prisma.user.count({ where: { status: 'ACTIVE' } }), prisma.allocation.count(), prisma.allocation.findMany({ where: { status: 'ACTIVE' } }), prisma.tradingPool.findMany(), prisma.payment.count({ where: { status: { in: ['PENDING','DETECTED','CONFIRMING','UNDER_REVIEW'] } } }), prisma.payment.findMany({ where: { status: 'COMPLETED' } }), prisma.withdrawal.count({ where: { status: { in: ['REQUESTED','UNDER_REVIEW'] } } }), prisma.withdrawal.findMany(), prisma.supportTicket.count({ where: { status: { in: ['OPEN','PENDING'] } } }), prisma.supportTicket.findMany({ where: { priority: 'Urgent' }, take: 5 }), prisma.auditLog.findMany({ include: { actor: true }, orderBy: { createdAt: 'desc' }, take: 8 }),
  ]);
  const activeCapital = activeAllocations.reduce((s, a) => s.plus(a.currentValue), new Prisma.Decimal(0));
  const completedPaymentVolume = completedPayments.reduce((s, p) => s.plus(p.receivedAmount ?? p.requestedAmount), new Prisma.Decimal(0));
  const withdrawalVolume = withdrawals.reduce((s, w) => s.plus(w.amount), new Prisma.Decimal(0));
  const poolUtilization = pools.length ? pools.reduce((s, p) => s + safeCapacityUtilization(Number(p.currentlyAllocated), Number(p.totalCapacity)), 0) / pools.length : 0;
  return { totalUsers, activeUsers, totalAllocations, activeCapital, poolUtilization, pendingPayments, completedPaymentVolume, pendingWithdrawals, withdrawalVolume, openTickets, alerts, auditLogs, pools };
}
export async function savePool(actorId: string, role: Role, formData: FormData, id?: string) {
  assertAdmin(role, id ? 'pools.update' : 'pools.create');
  const minimumAllocation = new Prisma.Decimal(String(formData.get('minimumAllocation') ?? '0'));
  const maximumAllocation = new Prisma.Decimal(String(formData.get('maximumAllocation') ?? '0'));
  const totalCapacity = new Prisma.Decimal(String(formData.get('totalCapacity') ?? '0'));
  const currentlyAllocated = id ? (await prisma.tradingPool.findUniqueOrThrow({ where: { id } })).currentlyAllocated : new Prisma.Decimal(0);
  if (minimumAllocation.lte(0) || maximumAllocation.lt(minimumAllocation) || totalCapacity.lt(currentlyAllocated)) throw new Error('Invalid pool financial configuration.');
  const data = { name: String(formData.get('name')), slug: String(formData.get('slug')), shortDescription: String(formData.get('shortDescription')), fullDescription: String(formData.get('fullDescription')), strategyDescription: String(formData.get('strategyDescription')), riskLevel: String(formData.get('riskLevel')) as never, status: String(formData.get('status') ?? 'DRAFT') as never, featured: formData.get('featured') === 'on', baseCurrency: String(formData.get('baseCurrency') ?? 'USDT'), minimumAllocation, maximumAllocation, totalCapacity, managementFeePercent: new Prisma.Decimal(String(formData.get('managementFeePercent') ?? '0')), performanceFeePercent: new Prisma.Decimal(String(formData.get('performanceFeePercent') ?? '0')), flexibleDuration: formData.get('flexibleDuration') === 'on', durationDays: Number(formData.get('durationDays') || 0) || null, heroImage: String(formData.get('heroImage') ?? ''), icon: String(formData.get('icon') ?? ''), displayOrder: Number(formData.get('displayOrder') || 0) };
  const pool = id ? await prisma.tradingPool.update({ where: { id }, data }) : await prisma.tradingPool.create({ data: { ...data, currentlyAllocated: 0 } });
  await audit(actorId, id ? 'pool.updated' : 'pool.created', 'TradingPool', pool.id, `${id ? 'Updated' : 'Created'} pool ${pool.name}`);
  return pool;
}
export async function setPoolStatus(actorId: string, role: Role, id: string, status: PoolStatus) { assertAdmin(role, 'pools.publish'); const pool = await prisma.tradingPool.update({ where: { id }, data: { status } }); await audit(actorId, 'pool.status_changed', 'TradingPool', id, `Pool status changed to ${status}`); return pool; }
export async function addPerformance(actorId: string, role: Role, formData: FormData) { assertAdmin(role, 'performance.manage'); const entry = await prisma.poolPerformance.upsert({ where: { poolId_date: { poolId: String(formData.get('poolId')), date: new Date(String(formData.get('date'))) } }, update: { nav: String(formData.get('nav')), dailyReturnPercent: String(formData.get('dailyReturnPercent')), cumulativeReturnPercent: String(formData.get('cumulativeReturnPercent')), benchmarkReturnPercent: String(formData.get('benchmarkReturnPercent')), drawdownPercent: String(formData.get('drawdownPercent')), assetsUnderManagement: String(formData.get('assetsUnderManagement')) }, create: { poolId: String(formData.get('poolId')), date: new Date(String(formData.get('date'))), nav: String(formData.get('nav')), dailyReturnPercent: String(formData.get('dailyReturnPercent')), cumulativeReturnPercent: String(formData.get('cumulativeReturnPercent')), benchmarkReturnPercent: String(formData.get('benchmarkReturnPercent')), drawdownPercent: String(formData.get('drawdownPercent')), assetsUnderManagement: String(formData.get('assetsUnderManagement')) } }); await audit(actorId, 'performance.upserted', 'PoolPerformance', entry.id, 'Performance history changed'); return entry; }
export async function adminAdvancePayment(actorId: string, role: Role, paymentReference: string, status: 'DETECTED'|'CONFIRMING'|'COMPLETED'|'UNDER_REVIEW') { assertAdmin(role, 'payments.manage'); if (status === 'UNDER_REVIEW') { const p = await prisma.payment.update({ where: { paymentReference }, data: { status: PaymentStatus.UNDER_REVIEW } }); await audit(actorId, 'payment.under_review', 'Payment', p.id, `Payment ${paymentReference} marked under review`); return p; } if (!isValidMockPaymentTransition(status)) throw new Error('Invalid mock payment transition.'); assertMockPaymentControlsEnabled(); const payment = await completeMockPayment(paymentReference, status); await audit(actorId, 'payment.mock_advanced', 'Payment', payment.id, `Mock payment advanced to ${status}`); return payment; }
export async function updateUserStatus(actorId: string, role: Role, userId: string, status: 'ACTIVE'|'SUSPENDED'|'RESTRICTED') { assertAdmin(role, 'users.manage'); const u = await prisma.user.update({ where: { id: userId }, data: { status } }); await audit(actorId, 'user.status_changed', 'User', userId, `User status changed to ${status}`); return u; }
export async function updateUserRole(actorId: string, role: Role, userId: string, nextRole: Role) { assertAdmin(role, 'users.roles.manage'); const u = await prisma.user.update({ where: { id: userId }, data: { role: nextRole } }); await audit(actorId, 'user.role_changed', 'User', userId, `User role changed to ${nextRole}`); return u; }
export async function updateSetting(actorId: string, role: Role, key: string, value: string) { assertAdmin(role, 'settings.manage'); const s = await prisma.platformSetting.upsert({ where: { key }, update: { value }, create: { key, value, description: 'Admin-managed operational setting' } }); await audit(actorId, 'setting.updated', 'PlatformSetting', s.id, `Setting ${key} updated`); return s; }
